[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
app_market = "FMqnbWG4pExkkXQjbtAiPmEFfsdopMfYnEaRT5pjnetZ"

[programs.localnet]
app_market = "FMqnbWG4pExkkXQjbtAiPmEFfsdopMfYnEaRT5pjnetZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/app-market"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# Trigger build
