[v1]
"solana-bench-streamer 1.18.20 (path+file:///private/tmp/solana-20241013-7811-qsf2k2/solana-1.18.20/bench-streamer)" = ["solana-bench-streamer"]
"solana-cli 1.18.20 (path+file:///private/tmp/solana-20241013-7811-qsf2k2/solana-1.18.20/cli)" = ["solana"]
"solana-faucet 1.18.20 (path+file:///private/tmp/solana-20241013-7811-qsf2k2/solana-1.18.20/faucet)" = ["solana-faucet"]
"solana-keygen 1.18.20 (path+file:///private/tmp/solana-20241013-7811-qsf2k2/solana-1.18.20/keygen)" = ["solana-keygen"]
"solana-log-analyzer 1.18.20 (path+file:///private/tmp/solana-20241013-7811-qsf2k2/solana-1.18.20/log-analyzer)" = ["solana-log-analyzer"]
"solana-net-shaper 1.18.20 (path+file:///private/tmp/solana-20241013-7811-qsf2k2/solana-1.18.20/net-shaper)" = ["solana-net-shaper"]
"solana-stake-accounts 1.18.20 (path+file:///private/tmp/solana-20241013-7811-qsf2k2/solana-1.18.20/stake-accounts)" = ["solana-stake-accounts"]
"solana-tokens 1.18.20 (path+file:///private/tmp/solana-20241013-7811-qsf2k2/solana-1.18.20/tokens)" = ["solana-tokens"]
"solana-validator 1.18.20 (path+file:///private/tmp/solana-20241013-7811-qsf2k2/solana-1.18.20/validator)" = ["solana-test-validator"]
"solana-watchtower 1.18.20 (path+file:///private/tmp/solana-20241013-7811-qsf2k2/solana-1.18.20/watchtower)" = ["solana-watchtower"]
